# Generated by Django 4.0.1 on 2022-01-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=50, null=True)),
                ('home_n', models.CharField(blank=True, max_length=10, null=True)),
                ('flat_n', models.CharField(blank=True, max_length=10, null=True)),
                ('cad_n', models.CharField(blank=True, max_length=20, null=True)),
                ('area_n', models.IntegerField(blank=True, null=True)),
                ('addi_info', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('serial_id', models.IntegerField(blank=True, null=True)),
                ('messages', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='hackapp.adresses')),
            ],
        ),
    ]
