# Generated by Django 4.0.1 on 2022-01-22 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='messages',
        ),
        migrations.AddField(
            model_name='user',
            name='adresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to='hackapp.adresses'),
        ),
    ]
