# Generated by Django 4.0.1 on 2022-01-22 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0002_remove_user_messages_user_adresses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adresses',
        ),
        migrations.AddField(
            model_name='adresses',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='hackapp.user'),
        ),
    ]
