# Generated by Django 4.0.1 on 2022-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0003_remove_user_adresses_adresses_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresses',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adresses',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
