# Generated by Django 4.0.1 on 2022-01-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackapp', '0005_user_addi_info_user_area_n_user_cad_n_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
